### ISSUE TITLE
Debug option cause app crash when path are absolute.

### ISSUE THREAD

**Issue by yourimiyi** [joscha/gulp-rewrite-css#36] opened 2016-04-07 07:38 UTC
`line 97 : newPath = mungePath(match, sourceFilePath, file);`

mungePath should return String or 'undefined' for newPath.
but, debug options enables make return gutil.log object.

`line 82 :      } else if (opt.debug) {`
`line 83 :        return gutil.log(magenta(PLUGIN_NAME), 'not rewriting absolute path for, magenta(match), 'in', magenta(sourceFilePath));`

Anyway, Thanks for great module!

**Comment by joscha** [comment] 2016-04-07 08:03
duplicate of #33. Can you write a fix for it @yourimiyi?

**Closed by joscha** 2016-04-07 08:03 UTC
